name: foodly_driver
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^11.0.0
  geocoding: ^2.0.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.3
  http: ^1.1.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  get_storage: ^2.1.1
  device_preview: ^1.1.0
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  syncfusion_flutter_charts: ^28.2.9
  flutter_local_notifications: ^17.2.2
  photo_view:
  cloud_firestore:
  firebase_storage:
  image_picker:
  location: ^7.0.0

  dio: ^5.5.0+1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  flutter_easyloading: ^3.0.5
  firebase_messaging:
  pull_to_refresh:
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/